/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewVendaPro;

import bean.ProdutoRsj;
import bean.VendaRsj;
import bean.VendaprodutoRsj;
import dao.ProdutoDAO;
import dao.VendaDAO;
import dao.VendaprodutoDAO;
import java.util.List;
import viewControle.VendaControle;

/**
 *
 * @author User
 */
public class JDlgVendaPedio extends javax.swing.JDialog {
JDLgVendas  jDlgVenda;
ProdutoRsj produtoRsj;
VendaControle vendaControle;

    /**
     * Creates new form JDlgVendaPedio
     */
    public JDlgVendaPedio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tools.Util.habilitar(false, jTxtTotal, jTxtvalorunitarioRsj);
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List lista = produtoDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
           jCboProdutoRsj.addItem((ProdutoRsj) lista.get(i)); }
    }
     public void setTelaAnterior(JDLgVendas jDlgVenda) {
        this.jDlgVenda = jDlgVenda;
        
    }
    public VendaprodutoRsj viewBean(){
    return null;
//                 VendaRsj Ven = new VendaRsj();    
//
//                 VendaDAO vdao = new VendaDAO();    
//                  
//        
//        // Ven.set(tools.Util.strDouble(jTxtvalorunitarioRsj.getText()) );
//        //Ven.set(tools.Util.strInt(jTxtQuantidadeRsj.getText()) );      
// //            Ven.setProduto((ProdutoRsj) jCboProdutoRsj.getSelectedItem());
////             Ven.setVenda((VendaRsj) vdao.busca(tools.Util.strInt(jDlgVenda.getIdVenda())));
////
//      
//        
//
//     
////        
//      return Ven;
//        
   }

     public VendaprodutoRsj beanviaw(VendaprodutoRsj Ven) {
        //string\/
        jTxtvalorunitarioRsj.setText(tools.Util.doubleStr(Ven.getValorunitarioRsj()) );
        jTxtQuantidadeRsj.setText(tools.Util.intStr(Ven.getQuantidadeRsj()) );
         jCboProdutoRsj.setSelectedItem(Ven.getProdutoRsj());


        

        return Ven;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBtnCancelar = new javax.swing.JButton();
        jBtnOk = new javax.swing.JButton();
        jTxtvalorunitarioRsj = new javax.swing.JTextField();
        jTxtQuantidadeRsj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboProdutoRsj = new javax.swing.JComboBox<ProdutoRsj>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("valor unitario");

        jLabel2.setText("quantidade");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnCancelar.setText("Cancelar");
        jPanel2.add(JBtnCancelar);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnOk);

        jTxtvalorunitarioRsj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtvalorunitarioRsjActionPerformed(evt);
            }
        });

        jLabel3.setText("total");

        jLabel4.setText("produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCboProdutoRsj, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtvalorunitarioRsj)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtQuantidadeRsj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboProdutoRsj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtvalorunitarioRsj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtQuantidadeRsj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtvalorunitarioRsjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtvalorunitarioRsjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtvalorunitarioRsjActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
       VendaprodutoRsj vem = viewBean();
        VendaprodutoDAO vendaprodutoDAO = new VendaprodutoDAO();
    
        
        
         if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
             vendaprodutoDAO.insert(vem);
       //      jDlgVenda.vendaControle.addBean(vem);
       
        
             
        } else {    
             vendaprodutoDAO.upedate(vem);
      //                  jDlgVenda.vendaControle.updateBean(jDlgVenda.getSelectedRowProd(), vem);

        }
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaPedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaPedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaPedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaPedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendaPedio dialog = new JDlgVendaPedio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox<ProdutoRsj> jCboProdutoRsj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtQuantidadeRsj;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtvalorunitarioRsj;
    // End of variables declaration//GEN-END:variables
}
