package bean;
// Generated 11/09/2024 09:05:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioRsj generated by hbm2java
 */
@Entity
@Table(name="usuario_rsj"
    ,catalog="db_rafael_jesus"
)
public class UsuarioRsj  implements java.io.Serializable {


     private int idusuarioRsj;
     private String nomeRsj;
     private String apelidoRsj;
     private String cpfRsj;
     private Date datanascimentoRsj;
     private String senhaRsj;
   //  private int nivelRsj;
     private String ativoRsj;

    public UsuarioRsj() {
    }

	
    public UsuarioRsj(int idusuarioRsj) {
        this.idusuarioRsj = idusuarioRsj;
    }
    public UsuarioRsj(int idusuarioRsj, String nomeRsj, String apelidoRsj, String cpfRsj, Date datanascimentoRsj, String senhaRsj, int nivelRsj, String ativoRsj) {
       this.idusuarioRsj = idusuarioRsj;
       this.nomeRsj = nomeRsj;
       this.apelidoRsj = apelidoRsj;
       this.cpfRsj = cpfRsj;
       this.datanascimentoRsj = datanascimentoRsj;
       this.senhaRsj = senhaRsj;
     //  this.nivelRsj = nivelRsj;
       this.ativoRsj = ativoRsj;
    }
   
     @Id 

    
    @Column(name="idusuario_rsj", unique=true, nullable=false)
    public int getIdusuarioRsj() {
        return this.idusuarioRsj;
    }
    
    public void setIdusuarioRsj(int idusuarioRsj) {
        this.idusuarioRsj = idusuarioRsj;
    }

    
    @Column(name="nome_rsj", length=50)
    public String getNomeRsj() {
        return this.nomeRsj;
    }
    
    public void setNomeRsj(String nomeRsj) {
        this.nomeRsj = nomeRsj;
    }

    
    @Column(name="apelido_rsj", length=45)
    public String getApelidoRsj() {
        return this.apelidoRsj;
    }
    
    public void setApelidoRsj(String apelidoRsj) {
        this.apelidoRsj = apelidoRsj;
    }

    
    @Column(name="cpf_rsj", length=14)
    public String getCpfRsj() {
        return this.cpfRsj;
    }
    
    public void setCpfRsj(String cpfRsj) {
        this.cpfRsj = cpfRsj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datanascimento_rsj", length=10)
    public Date getDatanascimentoRsj() {
        return this.datanascimentoRsj;
    }
    
    public void setDatanascimentoRsj(Date datanascimentoRsj) {
        this.datanascimentoRsj = datanascimentoRsj;
    }

    
    @Column(name="senha_rsj", length=45)
    public String getSenhaRsj() {
        return this.senhaRsj;
    }
    
    public void setSenhaRsj(String senhaRsj) {
        this.senhaRsj = senhaRsj;
    }

    
//    @Column(name="nivel_rsj")
//    public int getNivelRsj() {
//        return this.nivelRsj;
//    }
//    
//    public void setNivelRsj(int nivelRsj) {
//        this.nivelRsj = nivelRsj;
//    }

    
    @Column(name="ativo_rsj", length=1)
    public String getAtivoRsj() {
        return this.ativoRsj;
    }
    
    public void setAtivoRsj(String ativoRsj) {
        this.ativoRsj = ativoRsj;
    }

  @Override
     public String toString() {
return this.nomeRsj;
}
public boolean equals(Object object) {
if (object instanceof UsuarioRsj) {
UsuarioRsj atu = (UsuarioRsj) object;
if (this.getIdusuarioRsj()== atu.getIdusuarioRsj()) {
return true;
}
}
return false;
}


}


