package bean;
// Generated 27/07/2024 09:42:49 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaRsj generated by hbm2java
 */
@Entity
@Table(name = "venda_rsj",
         catalog = "db_rafael_jesus"
)
public class VendaRsj implements java.io.Serializable {

    private int idvendaRsj;
    private double totalRsj;
    private String formapagamentoRsj;
    private Date datavendaRsj;
    private String fkvendaprodutoRsj;

    public VendaRsj() {
    }

    public VendaRsj(int idvendaRsj) {
        this.idvendaRsj = idvendaRsj;
    }

    public VendaRsj(int idvendaRsj, double totalRsj, String formapagamentoRsj, Date datavendaRsj, String fkvendaprodutoRsj) {
        this.idvendaRsj = idvendaRsj;
        this.totalRsj = totalRsj;
        this.formapagamentoRsj = formapagamentoRsj;
        this.datavendaRsj = datavendaRsj;
        this.fkvendaprodutoRsj = fkvendaprodutoRsj;

    }

    @Id

    @Column(name = "idvenda_rsj", unique = true, nullable = false)
    public int getIdvendaRsj() {
        return this.idvendaRsj;
    }

    public void setIdvendaRsj(int idvendaRsj) {
        this.idvendaRsj = idvendaRsj;
    }

    @Column(name = "total_rsj", precision = 14)
    public double getTotalRsj() {
        return this.totalRsj;
    }

    public void setTotalRsj(double totalRsj) {
        this.totalRsj = totalRsj;
    }

    @Column(name = "formapagamento_rsj", length = 6)
    public String getFormapagamentoRsj() {
        return this.formapagamentoRsj;
    }

    public void setFormapagamentoRsj(String formapagamentoRsj) {
        this.formapagamentoRsj = formapagamentoRsj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datavenda_rsj", length = 10)
    public Date getDatavendaRsj() {
        return this.datavendaRsj;
    }

    public void setDatavendaRsj(Date datavendaRsj) {
        this.datavendaRsj = datavendaRsj;
    }

    @Column(name = "fkvendaproduto_rsj", length = 45)
    public String getFkvendaprodutoRsj() {
        return this.fkvendaprodutoRsj;
    }

    public void setFkvendaprodutoRsj(String fkvendaprodutoRsj) {
        this.fkvendaprodutoRsj = fkvendaprodutoRsj;
    }

}
