package bean;
// Generated 16/09/2024 12:26:42 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaRsj generated by hbm2java
 */
@Entity
@Table(name = "venda_rsj",
         catalog = "db_rafael_jesus"
)
public class VendaRsj implements java.io.Serializable {

    private int idvendaRsj;
    private ClienteRsj clienteRsj;
    private VendaprodutoRsj vendaprodutoRsj;
    private VendedorRsj vendedorRsj;
    private double totalRsj;
    private String formapagamentoRsj;
    private Date datavendaRsj;

    public VendaRsj() {
    }

    public VendaRsj(int idvendaRsj) {
        this.idvendaRsj = idvendaRsj;
    }

    public VendaRsj(int idvendaRsj, ClienteRsj clienteRsj, VendaprodutoRsj vendaprodutoRsj, VendedorRsj vendedorRsj, double totalRsj, String formapagamentoRsj, Date datavendaRsj, Set vendaprodutoRsjs) {
        this.idvendaRsj = idvendaRsj;
        this.clienteRsj = clienteRsj;
        this.vendaprodutoRsj = vendaprodutoRsj;
        this.vendedorRsj = vendedorRsj;
        this.totalRsj = totalRsj;
        this.formapagamentoRsj = formapagamentoRsj;
        this.datavendaRsj = datavendaRsj;

    }

    @Id

    @Column(name = "idvenda_rsj", unique = true, nullable = false)
    public int getIdvendaRsj() {
        return this.idvendaRsj;
    }

    public void setIdvendaRsj(int idvendaRsj) {
        this.idvendaRsj = idvendaRsj;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkcliente_rsj")
    public ClienteRsj getClienteRsj() {
        return this.clienteRsj;
    }

    public void setClienteRsj(ClienteRsj clienteRsj) {
        this.clienteRsj = clienteRsj;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkvendaproduto_rsj")
    public VendaprodutoRsj getVendaprodutoRsj() {
        return this.vendaprodutoRsj;
    }

    public void setVendaprodutoRsj(VendaprodutoRsj vendaprodutoRsj) {
        this.vendaprodutoRsj = vendaprodutoRsj;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkvendedor_rsj")
    public VendedorRsj getVendedorRsj() {
        return this.vendedorRsj;
    }

    public void setVendedorRsj(VendedorRsj vendedorRsj) {
        this.vendedorRsj = vendedorRsj;
    }

    @Column(name = "total_rsj", precision = 14)
    public double getTotalRsj() {
        return this.totalRsj;
    }

    public void setTotalRsj(double totalRsj) {
        this.totalRsj = totalRsj;
    }

    @Column(name = "formapagamento_rsj", length = 6)
    public String getFormapagamentoRsj() {
        return this.formapagamentoRsj;
    }

    public void setFormapagamentoRsj(String formapagamentoRsj) {
        this.formapagamentoRsj = formapagamentoRsj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datavenda_rsj", length = 10)
    public Date getDatavendaRsj() {
        return this.datavendaRsj;
    }

    public void setDatavendaRsj(Date datavendaRsj) {
        this.datavendaRsj = datavendaRsj;
    }

}
