package bean;
// Generated 16/09/2024 12:26:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendaprodutoRsj generated by hbm2java
 */
@Entity
@Table(name = "vendaproduto_rsj",
         catalog = "db_rafael_jesus"
)
public class VendaprodutoRsj implements java.io.Serializable {

    private int idvendaprodutoRsj;
    private ProdutoRsj produtoRsj;
    private VendaRsj vendaRsj;
    private Double valorunitarioRsj;
    private int quantidadeRsj;

    public VendaprodutoRsj() {
    }

    public VendaprodutoRsj(ProdutoRsj produtoRsj, VendaRsj vendaRsj, Double valorunitarioRsj, int quantidadeRsj, Set vendaRsjs) {
        this.produtoRsj = produtoRsj;
        this.vendaRsj = vendaRsj;
        this.valorunitarioRsj = valorunitarioRsj;
        this.quantidadeRsj = quantidadeRsj;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idvendaproduto_rsj", unique = true, nullable = false)
    public int getIdvendaprodutoRsj() {
        return this.idvendaprodutoRsj;
    }

    public void setIdvendaprodutoRsj(int idvendaprodutoRsj) {
        this.idvendaprodutoRsj = idvendaprodutoRsj;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkproduto_rsj")
    public ProdutoRsj getProdutoRsj() {
        return this.produtoRsj;
    }

    public void setProdutoRsj(ProdutoRsj produtoRsj) {
        this.produtoRsj = produtoRsj;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkvenda_rsj")
    public VendaRsj getVendaRsj() {
        return this.vendaRsj;
    }

    public void setVendaRsj(VendaRsj vendaRsj) {
        this.vendaRsj = vendaRsj;
    }

    @Column(name = "valorunitario_rsj", precision = 22, scale = 0)
    public Double getValorunitarioRsj() {
        return this.valorunitarioRsj;
    }

    public void setValorunitarioRsj(Double valorunitarioRsj) {
        this.valorunitarioRsj = valorunitarioRsj;
    }

    @Column(name = "quantidade_rsj")
    public int getQuantidadeRsj() {
        return this.quantidadeRsj;
    }

    public void setQuantidadeRsj(int quantidadeRsj) {
        this.quantidadeRsj = quantidadeRsj;
    }

}
